

######################## Target All ########################

### get all car types
GET http://localHost:8080/api/car-type HTTP/1.1

### add car type
POST http://localHost:8080/api/car-type HTTP/1.1
content-type: application/json

{
    "companyName": "tempCompanyName",
    "brandName": "tempBrandName",
    "year": "2018"
}

###################### Target Specific #####################

### get specific car type
GET http://localHost:8080/api/car-type/601877ea72ac659498aab9ed HTTP/1.1

### update specific car type
PATCH http://localHost:8080/api/car-type/601877ea72ac659498aab9ed HTTP/1.1
content-type: application/json

{
    "companyName": "change"
}

### add drive to a specific car type
POST http://localHost:8080/api/car-type/601877ea72ac659498aab9ed HTTP/1.1
content-type: application/json

{
    "carTypeId": "5ff9a07c2bef585608da7710",
    "driveRawData": [
      {
        "routeID": "5ff8e7412049ec4e8cfaf29b",
        "rawData": [
          {"lat": "35.43453", "long": "46.43453", "fuelCon": "6.42356", "speed": "92"}
        ]
      }
    ]
}

### delete specific car type
DELETE  http://localHost:8080/api/car-type/5ff9a07c2bef585608da7710 HTTP/1.1
