

######################## Target All ########################

### get all car types
GET http://localHost:8080/api/car-type HTTP/1.1

### add car type
POST http://localHost:8080/api/car-type HTTP/1.1
content-type: application/json

{
    "companyName": "tempCompanyName",
    "brandName": "tempBrandName",
    "year": "2018"
}

###################### Target Specific #####################

### get specific car type
GET http://localHost:8080/api/car-type/5ff8c4187d0c5254e8515a24 HTTP/1.1

### update specific car type
PATCH http://localHost:8080/api/car-type/5ff8c4187d0c5254e8515a24 HTTP/1.1
content-type: application/json

{
    "companyName": "change"
}

### add drive to a specific car type
POST http://localHost:8080/api/car-type/5ff8c4187d0c5254e8515a24 HTTP/1.1
content-type: application/json

{

}

### delete specific car type
DELETE  http://localHost:8080/api/car-type/5ff8c4187d0c5254e8515a24 HTTP/1.1
