

######################## Target All ########################

### get all car types
GET http://localhost:8080/api/car-type HTTP/1.1

### add car type
POST http://eedrive.cs.colman.ac.il/api/car-type HTTP/1.1
content-type: application/json

{
    "companyName": "tempCompanyName",
    "brandName": "tempBrandName",
    "year": "2018"
}

### add car type
POST http://localhost:8080/api/car-type HTTP/1.1
content-type: application/json

{
    "companyName": "tempCompanyName",
    "brandName": "tempBrandName",
    "year": "2018"
}

###################### Target Specific #####################

### get specific car type
GET http://localHost:8080/api/car-type/601877ea72ac659498aab9ed HTTP/1.1

### update specific car type
PATCH http://localHost:8080/api/car-type/601877ea72ac659498aab9ed HTTP/1.1
content-type: application/json

{
    "companyName": "change"
}

### add drive to a specific car type
POST http://localHost:8080/api/car-type/6019c57c9ab1697d0ce42b57 HTTP/1.1
content-type: application/json

{
    "carTypeId": "601877ea72ac659498aab9ed",
    "driveRawData": [
      {
        "routeID": "5ff8e7412049ec4e8cfaf29b",
        "rawData": [
          {"lat": "35.43453", "long": "46.43453", "fuelCon": "6.42356", "speed": "92"}
        ]
      }
    ]
}

### delete specific car type
DELETE  http://eedrive.cs.colman.ac.il/api/car-type/60851ca4e9bd0ae79feb2b14 HTTP/1.1

###
POST http://eedrive.cs.colman.ac.il/api/car-type/drive-csv/61070aa856b367077ea6e78f
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="driveDetails"; filename="driveDetails.csv"
Content-Type: text/csv

< ./EliavData/drive9.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--