
# Do not run this test until the testing DB is set.
######################## Target All ########################

### get all drive routes
GET http://eedrive.cs.colman.ac.il/api/drive HTTP/1.1

### add drive route
POST http://eedrive.cs.colman.ac.il/api/drive/ HTTP/1.1
content-type: application/json

{
  "carTypeId":"6059f2410799b82dc9dfcde4",
  "timeAndDate":"2021-03-16-23-26-03",
  "driverAssist":false,
  "carType":{"brand":"Mazda", "model":"Three", "year":"2004"},
  "driveRawData":[
    {
      "lat":"34.7667074",
      "lang":"0.06471659081139003",
      "fuelCons":[],
      "speeds":[]
    },
    {
      "lat":"34.7667179",
      "lang":"0.04102660471122144",
      "fuelCons":[5],
      "speeds":[5]
    }, 
    {
      "lat":"34.7667156",
      "lang":"0.008169966365734305",
      "fuelCons":["5"],
      "speeds":["5"]
    }
    ]
}

###################### Target Specific #####################

### delete specific car type
DELETE  http://localHost:8080/api/drive/6019ce2672fb079bfc6debf9 HTTP/1.1

### get specific drive route
GET http://localHost:8080/api/drive/60187d0c4bcc8a7f5c62fe8f HTTP/1.1

### update specific drive route
PATCH http://localHost:8080/api/drive/60187d0c4bcc8a7f5c62fe8f HTTP/1.1
content-type: application/json

{
    "driveRawData": "change"
}

