

######################## Target All ########################

### get all model routes
GET http://eedrive.cs.colman.ac.il/api/model-route HTTP/1.1

### add car model route
POST http://localHost:8080/api/model-route HTTP/1.1
content-type: application/json

{
    "routeStartingPoint": {"lat": "31.779875", "long": "34.668727"},
    "routeEndingPoint": {"lat": "31.787796", "long": "34.676816"}
}

###################### Target Specific #####################

### get specific model route
GET http://localHost:8080/api/model-route/6018804036613791e0fa80c0 HTTP/1.1

### update specific model route
PATCH http://localHost:8080/api/model-route/6018804c36613791e0fa80c1 HTTP/1.1
content-type: application/json

{
    "routeStartingPoint": {"lat": "32.43453", "long": "46.43453"}
}

### delete specific model route
DELETE  http://localHost:8080/api/model-route/6019aa0f1633c999409ddf2a HTTP/1.1
