

######################## Target All ########################

### get all model routes
GET http://eedrive.cs.colman.ac.il/api/model-route HTTP/1.1

### add car model route
POST http://localHost:8080/api/model-route HTTP/1.1
content-type: application/json

{
    "bL":{"lat": "", "long": ""}, 
    "bR":{"lat": "", "long": ""},
    "tL":{"lat": "", "long": ""}, 
    "tR":{"lat": "", "long": ""}, 
}

###################### Target Specific #####################

### get specific model route
GET http://localHost:8080/api/model-route/6084407a73789f47442cbf5f HTTP/1.1

### get specific model route 6084541743556de51e111e0a
POST http://eedrive.cs.colman.ac.il/api/model-route/createModel HTTP/1.1
content-type: application/json

{
    "routeID": "6084541743556de51e111e0a",
    "carTypeID":"60aa615870f5f89ebbce8919"
}

### update specific model route
PATCH http://localHost:8080/api/model-route/6018804c36613791e0fa80c1 HTTP/1.1
content-type: application/json

{
    "routeStartingPoint": {"lat": "32.43453", "long": "46.43453"}
}

### delete specific model route
DELETE  http://localHost:8080/api/model-route/608420586cb4f7257854f45f HTTP/1.1
