

######################## Target All ########################

### get all optimal models
GET http://localHost:8080/api/optimal-model HTTP/1.1

### add car optimal model
POST http://localHost:8080/api/optimal-model HTTP/1.1
content-type: application/json

{
    "routeID": "5ff8e7412049ec4e8cfaf29b",
    "vertices": [
      {
        "vertexId": "5ff8e7412049ec4e8cfaf29b",
        "lat": "35.43453",
        "long": "46.43453",
        "speed": "120"
      },
      {
        "vertexId": "5ff7e7413049ec4e9cfab39f",
        "lat": "38.43453",
        "long": "47.43453",
        "speed": "110"
      }
    ],
    "edges": [
      {
        "vertexA": "5ff8e7412049ec4e8cfaf29b",
        "vertexB": "5ff7e7413049ec4e9cfab39f",
        "fuelCon": "6.48235"
      }
    ]
}

###################### Target Specific #####################

### get specific optimal model
GET http://localHost:8080/api/optimal-model/601880b436613791e0fa80c2 HTTP/1.1

### update specific optimal model
PATCH http://localHost:8080/api/optimal-model/601880b436613791e0fa80c2 HTTP/1.1
content-type: application/json

{
    "edges": [
      {
        "vertexA": "5ff7e7413049ec4e9cfab39f",
        "vertexB": "5ff8e7412049ec4e8cfaf29b",
        "fuelCon": "6.48235"
      }
    ]
}

### delete specific optimal model
DELETE  http://localHost:8080/api/optimal-model/6018804c36613791e0fa80c1 HTTP/1.1
